# Generated by Django 3.1.1 on 2020-10-26 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomadapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('adv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maps', to='nomadapp.adventure')),
            ],
        ),
    ]
