# Generated by Django 3.1.1 on 2020-11-18 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nomadapp', '0003_segment_waypoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=512, null=True)),
                ('uploadTime', models.DateTimeField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='nomadapp.map')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('ts', models.DateTimeField(null=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nomadapp.photo')),
            ],
        ),
    ]
